name: Deploy To Replicate

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Cog
        uses: replicate/setup-cog@v1
        with:
          token: ${{ secrets.REPLICATE_TOKEN }}

      - name: Download plugins
        run: cog run scripts/clone_plugins.sh

      - name: Push to Replicate
        run: cog push r8.im/joe-aivatarz/comfyui-runner