name: Deploy To Replicate

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Maximize build space
        uses: AdityaGarg8/remove-unwanted-software@v3
        with:
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-large-packages: 'true'
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Setup Cog
        uses: replicate/setup-cog@v1.0.5
        with:
          token: ${{ secrets.REPLICATE_TOKEN }}
          install-cuda: false
          cog-version: "v0.9.6"
#      - name: Download plugins
#        run: scripts/clone_plugins.sh
#      - name: Build Docker Image
#        run: cog build -t joe-aivatarz/comfyui-runner:latest
#      - name: Download plugins
#        run: cog run scripts/clone_plugins.sh
      - name: Push to Replicate
        run: cog push