name: Deploy To Replicate

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 512
          swap-size-mb: 1024
          remove-dotnet: 'true'
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Cog
        uses: replicate/setup-cog@v1
        with:
          token: ${{ secrets.REPLICATE_TOKEN }}
          install-cuda: false

      - name: Download plugins
        run: cog run scripts/clone_plugins.sh

      - name: Push to Replicate
        run: cog push r8.im/joe-aivatarz/comfyui-runner